# Generated by Django 4.0.2 on 2022-02-11 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=20, verbose_name='email')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='password')),
                ('token', models.CharField(blank=True, max_length=20, null=True, verbose_name='token')),
            ],
            options={
                'db_table': 'auth',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('listId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'db_table': 'list',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='items')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='main.list', verbose_name='リスト')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
