# Generated by Django 4.0.2 on 2022-03-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('listId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'db_table': 'list',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='items')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='taskmanagement.list', verbose_name='リスト')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
