# Generated by Django 4.0.2 on 2022-03-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='List_TaskType',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Task_TaskType',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='TaskGroup_TaskType',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
