# Generated by Django 4.0.2 on 2022-04-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0002_remove_list_list_tasktype_remove_task_task_tasktype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='List_memo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='list',
            name='List_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='list',
            name='List_sortId',
            field=models.IntegerField(verbose_name='ソートキー'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_description',
            field=models.TextField(blank=True, null=True, verbose_name='タスクの内容'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Task_sortId',
            field=models.IntegerField(verbose_name='ソートキー'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='TaskGroup_name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='TaskGroup_sortId',
            field=models.IntegerField(verbose_name='ソートキー'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='TaskStatus_name',
            field=models.CharField(max_length=20, verbose_name='名前'),
        ),
    ]
